#Makefile pre zistenie Endianity a Priradenie int do char + zadanie 1
#Hannah Kuklovská
#Zadanie 1

CC = gcc
CFLAGS = -Wall -Wextra -pedantic

# Source files
ENDIAM_SOURCE = endiam.c
PRIRAD_SOURCE = prirad.c

# Executables
ENDIAM_OUTPUT = endiam
PRIRAD_OUTPUT = prirad

all: $(ENDIAM_OUTPUT) $(PRIRAD_OUTPUT) 

$(ENDIAM_OUTPUT): $(ENDIAM_SOURCE)
	$(CC) $(CFLAGS) -o $(ENDIAM_OUTPUT) $(ENDIAM_SOURCE)

$(PRIRAD_OUTPUT): $(PRIRAD_SOURCE)
	$(CC) $(CFLAGS) -o $(PRIRAD_OUTPUT) $(PRIRAD_SOURCE)


clean:
	rm -f $(ENDIAM_OUTPUT) $(PRIRAD_OUTPUT) 
