#Makefile pre zistenie Endianity a Priradenie int do char 
#Hannah Kuklovská
#Zadanie 1

CC=gcc
CFLAGS = -Wall -Werror

endiam: endiam.c
    $(CC) $(CFLAGS) -o endiam endiam.c

prirad: prirad.c
    $(CC) $(CFLAGS) -o prirad prirad.c